### ISSUE TITLE
Message: Forbidden!Configured service account doesn't have access. Service account may have been revoked

### ISSUE THREAD

**Issue by cmoulliard** [fabric8-quickstarts/spring-boot-ribbon#113]
The README should be updated to specify that a role must bne added to the client on Openshift
```
oc policy add-role-to-user view -n $(oc project -q) -z default
```
otherwise, the Fabric8 Kubernetes client can't discover the services

```
io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: GET at: https://kubernetes.default.svc/api/v1/namespaces/test/pods/spring-boot-ribbon-1-3gu7z. Message: Forbidden!Configured service account doesn't have access. Service account may have been revoked..
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.requestFailure(OperationSupport.java:319) ~[kubernetes-client-1.4.35.jar!/:na]
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.assertResponseCode(OperationSupport.java:266) ~[kubernetes-client-1.4.35.jar!/:na]
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:237) ~[kubernetes-client-1.4.35.jar!/:na]
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:230) ~[kubernetes-client-1.4.35.jar!/:na]
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleGet(OperationSupport.java:226) ~[kubernetes-client-1.4.35.jar!/:na]
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.handleGet(BaseOperation.java:686) ~[kubernetes-client-1.4.35.jar!/:na]
```

**Comment by yanhongwang** [comment]
Hi, @cmoulliard 

I also meet the same error message when I use Jenkins plugin (kubernetes:1.0).
And my platform is Ubuntu 16.04, not Openshift.
Could I ask how you solve?

Add role? But, the error message is about "service account"?

Thanks.

Hong
